### ISSUE TITLE
django-debug-toolbar breaks Huey's always_eager mode

### ISSUE THREAD

**Issue by PhilippMatthes** [st-tu-dresden/inloop#356] opened 2020-03-05 16:17 UTC
As denoted in https://github.com/coleifer/huey/issues/342 and in https://github.com/jazzband/django-debug-toolbar/issues/695#issuecomment-414113249, there was an issue in `django-debug-toolbar` which impacted the `always_eager` mode of Huey.

Expected behavior: Setting `always_eager` (in later versions of Huey named `immediate`) to `True` during testing should run all tasks immediately without connecting to the Redis service.
Actual behavior: Setting `always_eager` to `True` does not do anything. Tests, which test asynchronous functionalitites based on Huey, fail because they cannot connect to the non-existent Redis service.

I suggest the following solution: remove `django-debug-toolbar` from the developer dependencies, since the associated issue on `django-debug-toolbar` is open since *2015*.

**Comment by martinmo** [comment] 2020-03-06 13:59
After looking into this I must say that the linked bug reports are misleading. The test failure that you had in [build 1040](https://travis-ci.org/st-tu-dresden/inloop/jobs/658745445) is not caused by DJDT and there is no bug in Huey.

However, Huey's `lock_task(…)` context manager doesn't honor the `always_eager` setting and always tries to contact redis, as you have found out in #297. That `lock_task(…)` call can be seen [near the end of the stacktrace of the failed test](https://travis-ci.org/st-tu-dresden/inloop/jobs/658745445#L981).

And this is because we don't use it as it is intended to be used (= inside of functions decorated with `@task`/`@db_task`, see https://huey.readthedocs.io/en/1.11.0/api.html#Huey.lock_task). I'll create a separate issue and close this one as invalid.

Btw, we explicitely set `always_eager` (instead of its default, `settings.DEBUG`), because in tests,  Django uses a default setting of `DEBUG = True` regardless of what you set manually (see https://docs.djangoproject.com/en/3.0/topics/testing/overview/#other-test-conditions). This is probably surprising for many.

**Closed by martinmo** 2020-03-06 13:59 UTC
Labels: bug, invalid

**Comment by martinmo** [comment] 2020-03-06 14:32
> And this is because we don't use it as it is intended to be used

Now I'm really puzzled. The way we use it isn't wrong after all … the only options we would have is to get rid of the `lock_task(…)` calls or migrate to the newest Huey version, which offers a `BlackHoleStorage` storage that can be used during tests.
